Owl Carousel
mudit023/templates pull request #115
Opened 2022-10-14 12:50 UTC by Mahak008

Here is the screenshot of the feature added.
![Screenshot (331)](https://user-images.githubusercontent.com/88129955/195851068-aad3d9c9-af5e-4710-99c9-b1006204343a.png)

2022-10-14 13:44 UTC, Susaksham commented
> Here is the screenshot of the feature added. ![Screenshot (331)](https://user-images.githubusercontent.com/88129955/195851068-aad3d9c9-af5e-4710-99c9-b1006204343a.png)

Please add the readme and comments in all the files , There are also some files that are not rendering so check  the [template guidelines](https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md)

2022-10-14 13:54 UTC, Susaksham commented
Please add the readme , gif and comments in all the files , check the [template guidelines](https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md)

2022-10-14 13:54 UTC, Susaksham commented
> Here is the screenshot of the feature added. ![Screenshot (331)](https://user-images.githubusercontent.com/88129955/195851068-aad3d9c9-af5e-4710-99c9-b1006204343a.png)

Please add the readme , gif and comments in all the files , check the [template guidelines](https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md)

2022-10-14 17:41 UTC, Mahak008 commented
Ok @Susaksham

2022-10-15 11:11 UTC, Mahak008 commented
I am sorry, I closed this request by mistake. Kindly reconsider it once @mudit023

2022-10-15 11:16 UTC, mudit023 requested changes
Thanks for the contribution. Please follow our [template guidelines](https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md) and we'll merge your PR.

2022-10-15 11:16 UTC, mudit023 commented on Owl Carousel/Readme.md
> +
Please add a proper readme file like this: [example](https://github.com/mudit023/templates/blob/main/animated-newsletter/Readme.md)

2022-10-15 11:16 UTC, mudit023 commented on Owl Carousel/Readme.md
> +This code can be used to create moving cards like profile cards, blogs etc.
Add a gif of your template that shows how your template looks and behaves.

2022-10-15 11:16 UTC, mudit023 commented on Owl Carousel/index.html
> +        <div class="slider">
Add proper comments where ever needed. To make it easier for the user to use your template.

2022-10-15 11:16 UTC, mudit023 commented on Owl Carousel/styles.css
> +    margin-top: 5%;
make use of CSS variables.

2022-10-15 11:28 UTC, Mahak008 commented
> Thanks for the contribution. Please follow our [template guidelines](https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md) and we'll merge your PR.

Ok, I will made all the required changes. Thanks for your response.

2022-10-15 12:29 UTC, Mahak008 commented
@mudit023 @Susaksham Can you please help me out how can I make changes to the readme.md file. Since, I accidentally deleted the forked repo due to which I am unable to make changes to Readme.md .

2022-10-15 18:07 UTC, Susaksham commented
> @mudit023 @Susaksham Can you please help me out how can I make changes to the readme.md file. Since, I accidentally deleted the forked repo due to which I am unable to make changes to Readme.md .
@Mahak008 
if you are talking about upstreaming that is how you can do it 
![image](https://user-images.githubusercontent.com/97833029/196001683-47c8d0ee-5763-4d6e-9a23-e134b49535fe.png)

2022-10-16 13:52 UTC, mudit023 commented
@Mahak008 let me know if it's okay for you.

2022-10-16 14:40 UTC, Mahak008 commented
> @Mahak008 let me know if it's okay for you.

Yeah sure

2022-10-16 14:54 UTC, mudit023 commented
> > @Mahak008 let me know if it's okay for you.
> 
> Yeah sure

Okay. I'm closing this PR.

2022-10-16 14:54 UTC, closed without merging