Created a new newsletter component
mudit023/templates pull request #23
Opened 2022-04-12 18:47 UTC by imRajAryan09

2022-04-12 19:38 UTC, Programing-School approved these changes

2022-04-12 19:48 UTC, mudit023 requested changes
You have deleted the simple-profile-card template in the PR. Create a new PR.

2022-04-12 20:42 UTC, imRajAryan09 commented
I have deleted it in my forked branch. It won't affect this one

2022-04-12 20:43 UTC, closed without merging

2022-04-13 04:53 UTC, mudit023 commented
> I have deleted it in my forked branch. It won't affect this one

You are making a request to merge that branch with the main branch. It'll affect.